version: "3.8"
services:
  backend:
    build: ahogea/myapp-backend:latest
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    build: ahogea/myapp-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
